# Jekyll config file

# Site settings
title: SemDial 2025 – Bialogue
title_separator: "|"
description: >- # this means to ignore newlines until "baseurl:"
  SemDial 2025 Bialogue, the 29th Workshop on the Semantics and Pragmatics of Dialogue
search: true
url: semdial2025.github.io
repository: "semdial2025/semdial2025.github.io"
breadcrumbs: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dirt

include:
  - _pages

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

teaser: /assets/Sparrenburg.jpeg

defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values: 
      layout: splash
